apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue
  labels:
    app: blue
spec:
  selector:
    matchLabels:
      app: blue
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
      - image: shadabshah1680/multi-server:latest
        imagePullPolicy: Always
        name: blue
        ports:
        - containerPort: 80