apiVersion: v1
kind: ReplicationController
metadata:
  name: green
spec:
  replicas: 1
  selector:
    app: green
  template:
    metadata:
      name: green
      labels:
        app: green
    spec:
      containers:
      - name: green
        image: shadabshah1680/multi-server:blue_green_kubernetes
        ports:
        - containerPort: 80