apiVersion: apps/v1
kind: Deployment
metadata:
  name: green
  labels:
    app: green
spec:
  selector:
    matchLabels:
      app: green
  template:
    metadata:
      labels:
        app: green
    spec:
      containers:
      - image: shadabshah1680/green_image:latest
        imagePullPolicy: Always
        name: green
        ports:
        - containerPort: 80